# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-web
  labels:
    app: coturn-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn-web
  template:
    metadata:
      labels:
        app: coturn-web
    spec:
      serviceAccount: coturn-web
      terminationGracePeriodSeconds: 10
      containers:
        ###
        # HTTP api for serving json RTC configs.
        ###
        - name: coturn-web
          image: ghcr.io/selkies-project/selkies-gstreamer/coturn-web:latest
          imagePullPolicy: Always
          env:
            - name: TURN_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: turn-shared-secret
                  key: TURN_SHARED_SECRET
            - name: TURN_REALM
              valueFrom:
                secretKeyRef:
                  name: turn-shared-secret
                  key: TURN_REALM
            - name: "PORT"
              value: "8080"
            # Use external IP of LoadBalancer
            - name: TURN_EXTERNAL_IP
              valueFrom:
                secretKeyRef:
                  name: turn-shared-secret
                  key: TURN_EXTERNAL_IP
            - name: TURN_PORT
              value: "80"
            - name: TURN_ALT_PORT
              value: "443"
            # Name of the auth header to get user name from
            - name: AUTH_HEADER_NAME
              value: "x-goog-authenticated-user-email"
          readinessProbe:
            tcpSocket:
              port: 8080
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi