# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

timeout: 3600s

substitutions:
  _USE_CACHE: "true"
  _IMAGE_PREFIX: selkies-gstreamer
  _IMAGE_TAG: latest

tags:
  - selkies-gstreamer-images

# NOTE: in order to run the coturn-web image on Cloud Run, the image must be in GCR or Artifact Registry.
images: [
  # coturn
  'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:${_IMAGE_TAG}',
  'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:latest',
  # coturn-web
  'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:${_IMAGE_TAG}',
  'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:latest',
]

steps:
###
# Selkies Coturn image
###
- name: 'gcr.io/cloud-builders/docker'
  id: coturn-pull
  entrypoint: 'bash'
  args: ["-c", "if [ '${_USE_CACHE}' = 'true' ]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: coturn
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:latest',
            'coturn'
        ]
  waitFor:
    - coturn-pull
- name: 'gcr.io/cloud-builders/docker'
  id: coturn-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn:latest',
        ]
  waitFor:
    - coturn
###
# Selkies Coturn Web image
###
- name: 'gcr.io/cloud-builders/docker'
  id: coturn-web-pull
  entrypoint: 'bash'
  args: ["-c", "if [ '${_USE_CACHE}' = 'true' ]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/docker'
  id: coturn-web
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:latest',
            'coturn-web'
        ]
  waitFor:
    - coturn-web-pull
- name: 'gcr.io/cloud-builders/docker'
  id: coturn-web-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-coturn-web:latest',
        ]
  waitFor:
    - coturn-web