# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# This file incorporates work covered by the following copyright and
# permission notice:
#
#   Copyright 2019 Google LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

FROM coturn/coturn:alpine

USER root

RUN apk add -u --no-cache curl

COPY detect_external_ip.sh /usr/bin/detect_external_ip
RUN chmod +x /usr/bin/detect_external_ip

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

USER nobody:nogroup

ENTRYPOINT ["/entrypoint.sh"]
